--- 
stages: 
  - name: Build
    inputs: 
      - type: git
        branch: master
    triggers: 
      - type: commit
    jobs: 
      - name: Build
        type: builder
  - name: Deploy
    inputs: 
      - type: job
        stage: Build
        job: Build
    triggers: 
      - type: stage
    jobs: 
      - name: dev
        type: deployer
        script: |-
            #!/bin/bash
            cd game
            yarn install
            yarn build
            cp ../game/Staticfile ../game/dist/Staticfile
            cp ../game/manifest.yml ../game/dist/manifest.yml
            cd ../game/dist
            ibmcloud cf push
            # View logs
            ibmcloud  cf logs --recent
        target:
          region_id: ${CF_REGION_ID}
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          application: ${CF_APP}
          api_key: ${API_KEY}